wandb_version: 1

batch_size:
  value: 96
checkpoint_dir:
  value: ./checkpoints/
dataset_path:
  value: ./data/lipread_20_mp4/
dropout_p:
  value: 0.2
epochs:
  value: 35
feature_method:
  value: dlib
feature_size:
  value: 136
hidden_size:
  value: 1024
learning_rate:
  value: 1.525670780855177e-05
num_layers:
  value: 2
weight_decay:
  value: 1.0e-07
