wandb_version: 1

batch_size:
  value: 128
checkpoint_dir:
  value: ./checkpoints/
dataset_path:
  value: ./data/lipread_20_mp4/
dropout_p:
  value: 0.3
epochs:
  value: 35
feature_method:
  value: dlib
feature_size:
  value: 136
hidden_size:
  value: 512
learning_rate:
  value: 3.5930428998334594e-05
num_layers:
  value: 1
weight_decay:
  value: 0
