wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 128
checkpoint_dir:
  desc: null
  value: ./checkpoints/
dataset_path:
  desc: null
  value: ./data/lipread_20_mp4/
dropout_p:
  desc: null
  value: 0.25
epochs:
  desc: null
  value: 35
feature_method:
  desc: null
  value: dlib
feature_size:
  desc: null
  value: 136
hidden_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 7.583598421198349e-05
model:
  desc: null
  value: BiLSTM-LRW
n_workers:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 1.0e-06
