wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 128
checkpoint_dir:
  desc: null
  value: ./checkpoints/
dataset_path:
  desc: null
  value: ./data/lipread_20_mp4/
dropout_p:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 1000
feature_method:
  desc: null
  value: dlib
learning_rate:
  desc: null
  value: 0.01
model:
  desc: null
  value: LipNet-LRW
n_workers:
  desc: null
  value: 16
