wandb_version: 1

batch_size:
  value: 32
checkpoint_dir:
  value: ./checkpoints/
dataset_path:
  value: ./data/lipread_20_mp4/
dropout_p:
  value: 0.4
epochs:
  value: 35
feature_method:
  value: dlib
feature_size:
  value: 136
hidden_size:
  value: 256
lr:
  value: 0.045974772213394376
num_layers:
  value: 4
weight_decay:
  value: 1.0e-05
